### ISSUE TITLE
Exercises 8.4--10.4

### ISSUE THREAD

**Issue by akoontz11** [akoontz11/BIOL-6310-Fall2018#1]
Hi Will, 

I've listed out some questions I have on assignments 8.4, 9.5, and 10.4.

- **8.4, 1c**: I'm running an anova between a binomial and a standard linear regression to compare the two, but the results are a little sparse. Am I right to interpret the listed deviance values as deviance that's introduced by the binomial as compared to the NULL (in this case the regular regression)?

- **9.5, 1b**: Does the line 

`mixed.model <- with(data, lmer(happening ~ temp.change+trump.percent+ (1|State_abb)))`

account for the repeated measurements of temp.change and trump.percent within a state? Just trying to confirm I understand the random effects correctly...

- **9.5, 2**: I'm having some confusion as to what to put in for the h value (y values) in the abline call (abline(h=,lwd=3, col="red"))

- **10.4, 1a**: I can't run any stan_glmer commands because the rstanarm library won't load. I'd like to eventually solve that (it feels beyond my expertise), but for now: am I to use the same explanatory/response variable setup as in question #9?

Thanks for your help.

**Comment by willpearse** [comment]
The Binomial vs. regular regression question is a tricky one; just come by my office and talk to me about it as it's easier to describe than to type.

9.5 1b - yep, perfect!

9.5 2: put the power (the probability you would see a true effect if there were one) in the line. So not 95%, and not 5%, but the "other percentage" that I repeat a lot.

10.4 1a: Yes. It can be a pain to install sometimes (still easier than writing your own sampler though, I promise you!) - my advice would be to run it on `pris`...

**Comment by akoontz11** [comment]
Thanks for this, it helps. 

I'm still having some issue in understanding the power analysis question...the line here, I'm confused as to which function to use:

https://github.com/akoontz11/BIOL-6310-Fall2018/blob/2283f335ce102878f43844168af977d94b857059/Assignments/Exercises_9.5.R#L34

In our loop, we're generating two vectors of values drawn from a Normal distribution, with increasing numbers of observations and different means. And then we generate a p value in comparing those two vectors (which basically resemble distributions themselves?). But the ANOVA function doesn't work (understandably, as each item utilizes several values). I;m scratching my head as to which one we should use.

**Comment by willpearse** [comment]
No worries. Try a t-test - can't beat a classic in this case! :D
