### ISSUE TITLE
Exercise 11 Questions

### ISSUE THREAD

**Issue by akoontz11** [akoontz11/BIOL-6310-Fall2018#2]
Hi Will, 

I have a couple of questions regarding Exercise_11.5.

- The code you provided in the handout for setting up the "recent" year, i.e. 

`with(data, data$recent <- data$year > 1960)`

doesn't seem to work for me. When I try to pull out that recent year, I get the value of `NULL` (link [here](https://github.com/akoontz11/BIOL-6310-Fall2018/blob/0071a840166b5e508315223be795d14071cb378a/Assignments/Exercises_11.5.R#L8)). Any suggestions on how to extract those years?

- 1b) I'm getting negative AIC values. Am I wrong to deliver the response variable as the argument of the ARIMA functions?

Thanks as always, 
Austin K.

**Comment by willpearse** [comment]
Oh shite. Thank you for spotting this; that's a typo and it should read `data$recent <- data$year > 1960`. I'll change it on the handout now.

**Comment by willpearse** [comment]
...oh, hang on, I have the correct code on my end. Could you double-check the handout looks like that please?

**Comment by akoontz11** [comment]
My mistake, the code on the handout is just `data$recent <- data$year > 1960` (no with(data, ...) part). And of course as a result that line works...sorry for that mix up.

**Comment by willpearse** [comment]
I'm obviously appalled, and would like you to tender your resignation from the lab immediately. I, myself, have never made a typo in an R script :p

**Comment by akoontz11** [comment]
Ok but this is good because I am now getting an error when trying to run a GLS with the recent year data using the line [here](https://github.com/akoontz11/BIOL-6310-Fall2018/blob/73d012224958fb4b4e7d7d849b7448e40c942ec2/Assignments/Exercises_11.5.R#L25)

The error reads "covariate must have values within groups for "corAR1" objects".  Maybe I'm not using the correct value for the 'form' argument?

**Comment by willpearse** [comment]
OK, put `year` or whatever it is in there. `recent` is a discrete variable - you're testing the effect of `recent` while controlling for the temporal autocorrelation using the correlation structure.

**Comment by akoontz11** [comment]
Yes, that did the trick. Thank you. 

The result of my ANOVA on the 2 GLSs also generates negative AICs, and the values are rather similar to one another (which is not what I'd expect given the data), but I can at least keep going now. Thanks again for getting me past my own mistake.
