### ISSUE TITLE
Exercise 12.5

### ISSUE THREAD

**Issue by akoontz11** [akoontz11/BIOL-6310-Fall2018#3]
Hi Will, 

I'm having an issue in trying to generate a weights matrix for the data being used for the HW on spatial autocorrelation. 

Specifically, I'm using the line 

`neighbors <- knn2nb(knearneigh(data, k=8))`

to try and generate nearest neighbor values for the weights matrix, and I'm getting an error telling me that my data contains non-numeric elements (as it does). But I can't generate neighbor values for a single variable of my dataset, because it needs to be in a matrix format. 

I don't think I'm understanding the weights matrix correctly in the context of this dataset...do I need to generate based off of either the lat or long variables?

Thanks.

**Comment by willpearse** [comment]
Give it your spatial data object, not a plan `data.frame`, as an argument. In my handout I use `sp.data` with that function, not `data`. The difference is subtle, but it is important (frustratingly)

**Comment by akoontz11** [comment]
Thank you, that clarifies things a bit. I was able to generate a weights matrix off of the sp.points variable.

`neighbors <- knn2nb(knearneigh(sp.points, k=8))`
`weights <- nb2listw(neighbors)`

But now I'm encountering an issue in my calculating the Moran's I, line below:

`moran.test(data$max.temp, weights)`

I get the error "objects of different length", which I'm interpreting as the number of values of my variable and the number of cells in my weights matrix (or maybe one of the dimensions of the matrix?).  Do I need to subset sp.points before generating a weights matrix from it?

**Comment by willpearse** [comment]
This is because you use `na.omit` *after* you've made the spatial
data.frame - the spatial data.frame and the original data frame are no
longer the same (length). Does that make sense?

**Comment by akoontz11** [comment]
Sort of. I see how many rows are removed when `na.omit` is called on `data`, and I get that in calling that command, it causes my `sp.points` data.frame to be different in size from the `data` object, which causes the weights matrix to not match `data`.

But...how do I reduce the size of my spatial data.frame (`sp.points`) to match `data` with the NAs omitted? Because I generate `data` using 

`data <- data.frame(extract(r, sp.points))`

and if I then omit NAs and call the lines

`data$lat <- points$lat
data$long <- points$long`

I get an error telling me that the `points` data.frame is too large for the `data` object.

**Comment by willpearse** [comment]
This is all caused by the same problem: the moment you remove something, it's no longer the same length as the other things.

**Comment by akoontz11** [comment]
I'm sorry to have to keep bothering you on this, but I'm still unclear on this point. I understand the cause of the problem--I don't understand the solution. 

I need to create a spatial data.frame using the `data` **after** omitting NAs. If I used the lines below, would that work?

`new.points <- data.frame(expand.grid(data$lat, data$long))`
`coordinates(new.points) <- ~long+lat`
`neighbors <- knn2nb(knearneigh(new.points, k=8))`
`weights <- nb2listw(neighbors)`

I know that generating the weights matrix is computationally intense so I want to make sure I have the right idea before I go and crash anything...

Thanks for your time.

**Comment by willpearse** [comment]
Yes, doing it that way round would work

**Comment by willpearse** [comment]
I just sent you an email about this as well, I realise, but why don't you come by my office today at 10am? We can get all this figure out very quickly then, I think.

**Comment by akoontz11** [comment]
Will, I'm still having issues with rstanarm on Pris....when I call `library(rstanarm)`, I get the error message: 

package or namespace load failed for ‘rstanarm’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 namespace ‘Matrix’ 1.2-12 is already loaded, but >= 1.2.13 is required

But when I call `packageVersion("Matrix")`, I'm told Pris has 1.2.14, which should be alright. Any help appreciated.
