### ISSUE TITLE
Exercise 10.4

### ISSUE THREAD

**Issue by akoontz11** [akoontz11/BIOL-6310-Fall2018#4]
I have what's hopefully my last issue regarding the linear regression assignments. 

I'm struggling on the power analysis coding challenge at the end of Assignment 10.4, specifically the line sending the contour command--I'm unsure what values need to be specified for x and y. 

`contour(prop.signif, x=n.samps, y=eff.sizes, add=TRUE, nlevels=5)`

I assumed these need to be the unique values we generate in the lines above, but when sending the command, I get the error "no contour values". Let me know if you see anything amiss, and thanks.

**Comment by willpearse** [comment]
You want to plot something from the simulation you've created, and it
should also be the same thing that's appearing in the `image` call
preceding this. Does that help?

**Comment by akoontz11** [comment]
Yep, or at least it confirmed what I thought (I think the error was ultimately stemming from a typo in my code). 

I've committed this exercise to the repo, and I don't believe I'll need to make any other changes! So the uploaded versions should be final. 

Thanks again.
